### ISSUE TITLE
Namespace and silent classes

### ISSUE THREAD

**Issue by florianbouvot** [inuitcss/trumps.headings#4]
Hi, 
I don't know if this is the best way, I propose two PR to follow this discussion [Make inuitcss a little more opinionated? #18](https://github.com/inuitcss/CONTRIBUTING/issues/18)
- #2 : add utility namespace
- #3 : add utility namespace and remove silent classes

**Comment by anselmh** [comment]
Closed as this won’t be done in the current version but handled in the upcoming new major version.
