### ISSUE TITLE
ITCSS/BEMIT theme headings

### ISSUE THREAD

**Issue by kaydwithers** [inuitcss/trumps.headings#8]
I'm working on a large project that constantly changes with new styling almost every year. Our typography and heading sizes change but we need to keep our legacy CSS code for older pages. What would be the best method for working with legacy headings?

We are about to try..

`_themes.2015.scss`
`_themes.2016.scss` 

`<div class="t-alpha  t-text-red">` 2015 theme styling
`<div class="t2-alpha  t2-text-red">` 2016 theme styling

But I'm not sure how to go about this with heading trumps because our themes are lower specificity. Should we just not use heading trumps?

**Comment by csshugs** [comment]
@kaydwithers My advise would be not to change the classes on the headings elements itself at all.

As I understood the principle of themes (in Harrys understanding), it is used for scoping a much wider context of your UI than just giving the elements itself a `t-` theming class. I.e. giving the `<body>` element a theming class and scope everything from there. E.g.:

``` html
<body class="t-2015">
    ...
    <h3 class="alpha text-red">2015 theme styling</h3>
    ...
</body>
```

``` html
<body class="t-2016">
    ...
    <h3 class="alpha text-red">2016 theme styling</h3>
    ...
</body>
```

This way your markup differs in just one place and you can style your headings differently in your Sass:

``` scss
.alpha {
    font-size: $heading-size-1;

    .t-2015 & {
        font-size: $heading-size-1--2015;
    }

    .t-2016 & {
        font-size: $heading-size-1--2016;
    }

}
```

> Should we just not use heading trumps?

Of course, you can't do this with the inuit-headings module, so yeah, I would suggest not using it. That's the great thing about inuit. You don't have to use everything. Leave out the bits you don't need or which don't fit your needs like in this case.
